services:
  verdestats:
    build: .
    image: timo348/verdestats:latest
    container_name: verdestats
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "30008:3000"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - verdestats-net

volumes:
  verdestats-uploads:

networks:
  verdestats-net:
    driver: bridge
